yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('my_follow/', views.my_follow, name='my_follow'),
    path('my_follower/', views.my_follower, name='my_follower')
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeDoneView, PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        views.PassChange.as_view(),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.PassReset.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.NewPassReset.as_view(),
        name='password_reset_token'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = settings.CSRF_FAILURE_VIEW
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
    <p>© {% now "Y" %} Copyright <span style="color:red">Blog</span>Post</p>
</div>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:white">Blog</span>Post
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:my_follow' %}active{% endif %}"
               href="{% url 'posts:my_follow' %}">Мои подписки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:my_follower' %}active{% endif %}"
               href="{% url 'posts:my_follower' %}">Мои подписчики</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
               href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
               href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == "posts:profile" %}active{% endif %}"
              href="{% url "posts:profile" request.user.username %}">Мой профиль</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      <p>
        {{ comment.created }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/post_template.html
{% load thumbnail %}
<article>
    <ul>
        <li>
            Автор: <a href="{% url "posts:profile" post.author.username %}" style="color: #1e2125; text-decoration:none "><b>{{ post.author.get_full_name}}</b></a>
        </li>
        {% if post.group %}
          <li>
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}" style="color: #1e2125; text-decoration: none"><b>{{ post.group.title }}</b></a>
          </li>
        {% endif %}
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li>
            <a href="{% url "posts:post_detail" post.id %}" style="color: #1e2125; text-decoration:none"><b>Перейти на страницу поста</b></a>
        </li>
    </ul>
    {% thumbnail post.image "1200x600"  upscale=True as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
</article>

yatube/templates/includes/switcher.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}"
             href="{% url 'posts:index' %}"><b>Все авторы</b></a>
        </li>
      <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:follow_index' %}active{% endif %}"
             href="{% url 'posts:follow_index' %}"><b>Избранные авторы</b></a>
        </li>
    </ul>
  </div>
{% endif %}
{% endwith %}