yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('my_follow/', views.my_follow, name='my_follow'),
    path('my_follower/', views.my_follower, name='my_follower')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = settings.CSRF_FAILURE_VIEW
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q, F, CheckConstraint, UniqueConstraint


User = get_user_model()


class Post(models.Model):

    FIRST_POST_CHAR = 15  # первые 15 символов для метода STR

    text = models.TextField(
        verbose_name='Текст статьи',
        help_text='Напишите вашу статью.'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор статьи',
        help_text='Укажите автора'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Укажите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Публикации авторов'

    def __str__(self):
        return self.text[:self.FIRST_POST_CHAR]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группа',
        help_text='Укажите название группы'
    )
    slug = models.SlugField(
        max_length=250,
        unique=True,
        verbose_name='URL',
        help_text='Укажите адрес группы'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Укажите описание группы'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите ваш комментарий'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )

    def __str__(self):
        return self.post

    class Meta:
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            UniqueConstraint(fields=['user', 'author'], name='unique_follow'),
            CheckConstraint(check=~Q(user=F('author')),
                            name='subscribe_to_yourself')
        ]

        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user} -> {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


def get_page_context(queryset, page):
    paginator = Paginator(queryset, settings.POSTS_IN_PAGE)
    page_obj = paginator.get_page(page)
    return page_obj


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': get_page_context(posts, request.GET.get('page')),
    }
    return render(request, template, context)


def group_post(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': get_page_context(posts, request.GET.get('page')),
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'following': following,
        'page_obj': get_page_context(posts, request.GET.get('page')),
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = (
        get_object_or_404
        (Post.objects.select_related('author', 'group'), pk=post_id)
    )
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'comments': comments,
        'form': CommentForm()
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', post.author.username)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = (
        get_object_or_404
        (Post.objects.select_related('author', 'group'), pk=post_id)
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post,)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    return render(request, template, {'form': form, 'is_edit': True, })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(
        author__following__user=request.user).select_related('author', 'group')
    context = {
        'page_obj': get_page_context(posts, request.GET.get('page')),
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=following).delete()
    return redirect('posts:profile', username=username)


@login_required
def my_follow(request):
    template = 'posts/follow_page.html'
    authors = request.user.follower.select_related('author')
    context = {
        'page_obj': get_page_context(authors, request.GET.get('page')),
        'is_edit': True
    }
    return render(request, template,  context)


@login_required
def my_follower(request):
    template = 'posts/follow_page.html'
    authors = request.user.following.select_related('author')
    context = {
        'page_obj': get_page_context(authors, request.GET.get('page')),
    }
    return render(request, template,  context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
        </div>
          <div class="card-body">
              {% load user_filters %}
              <form method="post"
              {% if action_url %}
              action="{% url action_url %}"
              {% endif %}
              enctype="multipart/form-data">
              <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group row my-3 p-3">
                     <label for="{{ field.id_for_label }}">
                         {{ field.label }}
                           {% if field.field.required %}
                              <span class="required text-danger">*</span>
                            {% endif %}
                     </label>
                     {{ field|addclass:'form-control' }}
                     {% if field.help_text %}
                       <small
                        id="{{ field.id_for_label }}-help"
                        class="form-text text-muted"
                       >
                        {{ field.help_text|safe }}
                       </small>
                     {% endif %}
                    </div>
                  {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Посты любимых авторов
{% endblock %}
{% block content %}
  <h1>Посты любимых авторов</h1>
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/post_template.html' %}
  {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/follow_page.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        Мои подписки
    {% else %}
        Мои подписчики
    {% endif %}
{% endblock %}
{% block content %}
    {% for follow in page_obj %}
      {% if is_edit %}
        <h1>
          <a href="{% url "posts:profile" follow.author.username %}" style="color: #1e2125; text-decoration:none"  >{{ follow.author.get_full_name}}</a>
          </a>
        </h1>
        <h3>Всего постов: {{ follow.author.posts.count }} </h3>
          <a
           class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' follow.author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <h1>
          <a href="{% url "posts:profile" follow.user.username %}" style="color: #1e2125; text-decoration:none"  >{{ follow.user.get_full_name}}</a>
          </a>
        </h1>
        <h3>Всего постов: {{ follow.user.posts.count }} </h3>
      {% endif %}
    {% endfor %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
      {{group.description}}
  </p>
  {% for post in page_obj %}
    {% include 'includes/post_template.html'  %}
  {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% load cache %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
  {% cache 20 index_page page_obj.number  %}
  {% for post in page_obj %}
    {% include 'includes/post_template.html' %}
  {% endfor %}
  {% endcache %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
      {% load thumbnail %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                  Группа: {{ group.title }}
                  <a href="{% url 'posts:group_list' post.group.slug %}" style="color: #1e2125; text-decoration: none"><b>все записи группы</b></a>
              </li>
            {% endif %}
            <li class="list-group-item">
                Автор: <a href="{% url "posts:profile" post.author.username %}" style="color: #1e2125; text-decoration: none"><b>{{ post.author.get_full_name}}</b></a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ post.author.posts.count }} </span>
            </li>
            {% if post.author %}
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}" style="color: #1e2125; text-decoration: none">
                    <b>Все посты пользователя</b>
                </a>
              </li>
            {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "1200x600"  upscale=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% include 'includes/post_comment.html'  %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
    {% if user.username != author.username %}
      {% if following %}
        <a
           class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
    {% for post in page_obj %}
      {% include 'includes/post_template.html' %}
    {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}